sonar.projectKey=lusky3_flixor_tizen
sonar.projectName=Flixor Tizen
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/__tests__/setup.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json
sonar.sourceEncoding=UTF-8
